"""
محرك الربط المتقدم - دعم And64InlineHook, MSHook, KittyMemory, Frida
"""

import os
import json
import subprocess
import tempfile
from typing import Dict, List, Optional, Tuple
from infrastructure.logger import app_logger
from infrastructure.file_system import FileSystem


class HookEngine:
    """محرك الربط والدوال"""

    @staticmethod
    def generate_cpp_hook(offset: int, hook_code: str, return_type: str = "void") -> str:
        return """
#include <cstdint>
#include <cstdio>
#include "And64InlineHook.h"

{return_type} (*orig_function)(void* instance);

{return_type} hook_function(void* instance) {{
    orig_function(instance);
    {hook_code}
}}

void install_hook() {{
    void* target = (void*)({offset});
    A64HookFunction(target, (void*)hook_function, (void**)&orig_function);
}}
""".format(return_type=return_type, hook_code=hook_code, offset=hex(offset))

    @staticmethod
    def generate_kittymemory_patch(offset: int, new_bytes: str, library: str = "libil2cpp.so") -> str:
        return """
#include "KittyMemory/KittyMemory.h"

void apply_patch() {{
    uintptr_t addr = KittyMemory::getAbsoluteAddress("{library}", {offset});
    KittyMemory::writeHex(addr, "{new_bytes}");
}}
""".format(library=library, offset=hex(offset), new_bytes=new_bytes)

    @staticmethod
    def generate_frida_script(script_name: str, hooks: List[Dict]) -> str:
        lines = [
            "// Frida Script: {0}".format(script_name),
            "// Generated by ProokSuite",
            "",
            "Java.perform(function() {",
            '    console.log("[*] {0} loaded");'.format(script_name),
            ""
        ]

        for hook in hooks:
            class_name = hook.get("class", "")
            method_name = hook.get("method", "")
            on_enter = hook.get("onEnter", "")
            on_leave = hook.get("onLeave", "")

            if class_name and method_name:
                lines.append('    var targetClass = Java.use("{0}");'.format(class_name))
                lines.append('    targetClass.{0}.implementation = function() {{'.format(method_name))
                lines.append('        console.log("[*] {0} called");'.format(method_name))
                if on_enter:
                    lines.append('        {0}'.format(on_enter))
                lines.append('        var result = this.{0}.apply(this, arguments);'.format(method_name))
                if on_leave:
                    lines.append('        {0}'.format(on_leave))
                lines.append('        return result;')
                lines.append('    };')
                lines.append('')

        lines.append('    console.log("[*] Hooks installed");')
        lines.append('});')

        return '\n'.join(lines)

    @staticmethod
    def generate_frida_il2cpp_script(script_name: str, hooks: List[Dict]) -> str:
        lines = [
            "// Frida IL2CPP Script: {0}".format(script_name),
            "// Generated by ProokSuite",
            "",
            "Il2Cpp.perform(function() {",
            '    console.log("[*] {0} loaded");'.format(script_name),
            ""
        ]

        for hook in hooks:
            class_name = hook.get("class", "")
            method_name = hook.get("method", "")
            on_enter = hook.get("onEnter", "")
            on_leave = hook.get("onLeave", "")

            if class_name and method_name:
                lines.append('    var targetClass = Il2Cpp.Domain.assembly("GameAssembly").image.class("{0}");'.format(class_name))
                lines.append('    targetClass.method("{0}").implementation = function() {{'.format(method_name))
                lines.append('        console.log("[*] {0} called");'.format(method_name))
                if on_enter:
                    lines.append('        {0}'.format(on_enter))
                lines.append('        var result = this.{0}.apply(this, arguments);'.format(method_name))
                if on_leave:
                    lines.append('        {0}'.format(on_leave))
                lines.append('        return result;')
                lines.append('    };')
                lines.append('')

        lines.append('    console.log("[*] Hooks installed");')
        lines.append('});')

        return '\n'.join(lines)

    @staticmethod
    def run_frida_script(package_name: str, script_content: str) -> bool:
        try:
            import frida
            device = frida.get_usb_device()
            session = device.attach(package_name)
            script = session.create_script(script_content)
            script.load()
            app_logger.info("Frida script loaded on {0}".format(package_name))
            return True
        except ImportError:
            app_logger.error("Frida not installed. Install: pip install frida-tools")
            return False
        except Exception as e:
            app_logger.error("Frida error: {0}".format(e))
            return False

    @staticmethod
    def generate_mod_menu_template(menu_name: str, features: List[Dict]) -> str:
        lines = [
            "// Mod Menu: {0}".format(menu_name),
            "// Generated by ProokSuite",
            "",
            '#include "KittyMemory/KittyMemory.h"',
            '#include "ModMenu.h"',
            "",
            "void hack_thread() {",
            '    while (!KittyMemory::isLibraryLoaded("libil2cpp.so")) {',
            '        sleep(1);',
            '    }',
            "",
            '    init_menu("{0}");'.format(menu_name),
            ""
        ]

        for idx, feature in enumerate(features):
            name = feature.get("name", "Feature_{0}".format(idx))
            ftype = feature.get("type", "bool")
            default = feature.get("default", "false")
            offset = feature.get("offset", "0x0")
            library = feature.get("library", "libil2cpp.so")

            if ftype == "bool":
                lines.append('    bool feature_{0} = {1};'.format(idx, default))
                lines.append('    TOGGLE("{0}", feature_{1}, "{2}");'.format(name, idx, offset))
                lines.append('    if (feature_{0}) {{'.format(idx))
                lines.append('        KittyMemory::writeHex(')
                lines.append('            KittyMemory::getAbsoluteAddress("{0}", {1}),'.format(library, offset))
                lines.append('            "00 00 80 3F"')
                lines.append('        );')
                lines.append('    }')
            elif ftype == "int":
                lines.append('    int feature_{0}_value = {1};'.format(idx, default))
                lines.append('    SEEK_BAR("{0}", feature_{1}_value, 0, 9999, "{2}");'.format(name, idx, offset))
                lines.append('    KittyMemory::writeInt(')
                lines.append('        KittyMemory::getAbsoluteAddress("{0}", {1}),'.format(library, offset))
                lines.append('        feature_{0}_value'.format(idx))
                lines.append('    );')
            elif ftype == "float":
                lines.append('    float feature_{0}_value = {1}f;'.format(idx, default))
                lines.append('    SEEK_BAR("{0}", feature_{1}_value, 0.0f, 9999.0f, "{2}");'.format(name, idx, offset))
                lines.append('    KittyMemory::writeFloat(')
                lines.append('        KittyMemory::getAbsoluteAddress("{0}", {1}),'.format(library, offset))
                lines.append('        feature_{0}_value'.format(idx))
                lines.append('    );')
            lines.append('')

        lines.append('    while (true) {')
        lines.append('        update_menu();')
        lines.append('        sleep(1);')
        lines.append('    }')
        lines.append('}')

        return '\n'.join(lines)