"""
بناء قائمة التعديل - إنشاء قوائم تعديل احترافية
"""

import os
import json
import zipfile
import tempfile
import shutil
from typing import List, Dict, Optional
from infrastructure.logger import app_logger
from infrastructure.file_system import FileSystem


class ModMenuBuilder:
    """Building professional mod menus"""

    @staticmethod
    def create_mod_menu_apk(original_apk: str, output_apk: str, menu_config: Dict) -> bool:
        try:
            temp_dir = tempfile.mkdtemp(prefix="prook_menu_")
            with zipfile.ZipFile(original_apk, 'r') as apk_zip:
                apk_zip.extractall(temp_dir)
            
            menu_files = ModMenuBuilder._generate_menu_files(menu_config)
            
            for file_path, content in menu_files.items():
                full_path = os.path.join(temp_dir, file_path)
                os.makedirs(os.path.dirname(full_path), exist_ok=True)
                with open(full_path, 'w', encoding='utf-8') as f:
                    f.write(content)
            
            with zipfile.ZipFile(output_apk, 'w', zipfile.ZIP_DEFLATED) as new_apk:
                for root, dirs, files in os.walk(temp_dir):
                    for file in files:
                        file_path = os.path.join(root, file)
                        arcname = os.path.relpath(file_path, temp_dir)
                        new_apk.write(file_path, arcname)
            
            shutil.rmtree(temp_dir, ignore_errors=True)
            
            app_logger.info("Mod menu APK created: {0}".format(output_apk))
            return True
            
        except Exception as e:
            app_logger.error("Error creating mod menu APK: {0}".format(e))
            return False

    @staticmethod
    def _generate_menu_files(config: Dict) -> Dict[str, str]:
        files = {}
        
        menu_name = config.get("name", "ProokSuite Mod Menu")
        features = config.get("features", [])
        
        cpp_code = ModMenuBuilder._generate_menu_cpp(menu_name, features)
        files["jni/modmenu.cpp"] = cpp_code
        
        android_mk = '''
LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)
LOCAL_MODULE := modmenu
LOCAL_SRC_FILES := modmenu.cpp
LOCAL_LDLIBS := -llog
LOCAL_CPPFLAGS := -std=c++17
include $(BUILD_SHARED_LIBRARY)
'''
        files["jni/Android.mk"] = android_mk
        
        application_mk = '''
APP_ABI := armeabi-v7a arm64-v8a
APP_PLATFORM := android-16
APP_STL := c++_shared
'''
        files["jni/Application.mk"] = application_mk
        
        return files

    @staticmethod
    def _generate_menu_cpp(menu_name: str, features: List[Dict]) -> str:
        lines = [
            "// Mod Menu: {0}".format(menu_name),
            "// Generated by ProokSuite",
            "",
            '#include "KittyMemory/KittyMemory.h"',
            '#include "And64InlineHook.h"',
            '#include "ModMenu.h"',
            "",
            "void hack_thread() {",
            '    while (!KittyMemory::isLibraryLoaded("libil2cpp.so")) {',
            '        sleep(1);',
            '    }',
            "",
            '    init_menu("{0}");'.format(menu_name),
            ""
        ]

        for idx, feature in enumerate(features):
            name = feature.get("name", "Feature_{0}".format(idx))
            ftype = feature.get("type", "bool")
            default = feature.get("default", "false")
            offset = feature.get("offset", "0x0")
            library = feature.get("library", "libil2cpp.so")

            if ftype == "bool":
                lines.append('    bool feature_{0} = {1};'.format(idx, default))
                lines.append('    TOGGLE("{0}", feature_{1}, "{2}");'.format(name, idx, offset))
                lines.append('    if (feature_{0}) {{'.format(idx))
                lines.append('        KittyMemory::writeHex(')
                lines.append('            KittyMemory::getAbsoluteAddress("{0}", {1}),'.format(library, offset))
                lines.append('            "00 00 80 3F"')
                lines.append('        );')
                lines.append('    }')
            elif ftype == "int":
                lines.append('    int feature_{0}_value = {1};'.format(idx, default))
                lines.append('    SEEK_BAR("{0}", feature_{1}_value, 0, 9999, "{2}");'.format(name, idx, offset))
                lines.append('    KittyMemory::writeInt(')
                lines.append('        KittyMemory::getAbsoluteAddress("{0}", {1}),'.format(library, offset))
                lines.append('        feature_{0}_value'.format(idx))
                lines.append('    );')
            elif ftype == "float":
                lines.append('    float feature_{0}_value = {1}f;'.format(idx, default))
                lines.append('    SEEK_BAR("{0}", feature_{1}_value, 0.0f, 9999.0f, "{2}");'.format(name, idx, offset))
                lines.append('    KittyMemory::writeFloat(')
                lines.append('        KittyMemory::getAbsoluteAddress("{0}", {1}),'.format(library, offset))
                lines.append('        feature_{0}_value'.format(idx))
                lines.append('    );')
            lines.append('')

        lines.append('    while (true) {')
        lines.append('        update_menu();')
        lines.append('        sleep(1);')
        lines.append('    }')
        lines.append('}')

        return '\n'.join(lines)